name: Trivy FS Scan

on:
  workflow_call:
    inputs:
      scan-path:
        description: "Path to scan (default: current directory)"
        required: false
        default: "."
        type: string

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db

      - name: Run Trivy FS Scan with custom HTML template
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: fs
          scan-ref: ${{ inputs.scan-path }}
          format: template
          template: https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
          output: trivy-fs-report.html

      - name: Upload Trivy FS Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.html
